sudo: required
language: python
env:
- ARCH=amd64
- ARCH=armhf
services:
- docker
before_install:
- docker pull sanji/mosquitto-dev:latest
- docker pull sanji/mosquitto-dev:armhf
script:
- bash build.sh
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: sCf9KTRRu97NNjTz1hl/OsyhEIwNq09Qkgy9CZou/i/pgC9Zku+0OyKLr0RXzzW5aiXKR7w3rSphuYa99EiGn+TEGtvA+rgK2Y6ppfv37QVjI+l+50n0tMQK7J0YBLD//PZoKKvuGgCPfaCDd57Gfj4GHXK0YBSFX4P1/OrVs+OhG6puy6HK33gDSPLk0EYZqxuS4bkO7XyI9WLe2iO2lWq41st2iL+6F3LOGPlPAZ7eLM2Ksh2CzXDuyasB37z2ojJU6RhTuoR80xG8IskTeM+u5DCLU6GvVRcz77BAFUHs283HvCh9SwUm+hXEGbv5em6g8ZncfMQrUz5ugvGpszAaQ/yNM4IDG/cHZf0D93reQfI27RLo3xjWle4b+AWSd8n+08Ob1wBoR2fMrXSfpE7OM+DYfkFlpAge30d6BVKVPu5MkcleMcgSNjjXTLKGv4JfjsBb9/FMdr+rijLPRfu6IcnaX6fmlzNv8RHE8VLKzXLevn6vjScSJfjEM+SY9VZxpdNvpG4aSR4TE2yMoGDvBYPk+vEgNS2sMYivTOXpbHcASVGLmtsavEdXcd1FKPHQ7xJPwHQmzlD4oIq7O/un5oqKVcKiKP6VJ5Uzv5bLrmsxH8zKLHE4A976rvIO84aywGxu4nnZaqxgwagt4lEe/lg0YvHHai4No0A3z2o=
  file_glob: true
  file: workspace/*.deb
  on:
    repo: Sanji-IO/mosquitto-deb
    tags: true

- provider: bintray
  file: travis_bintray_deb_amd64.json
  user: yulun
  dry-run: true
  on:
    condition: $ARCH = amd64
  key:
    secure: s5MLdBxFW3IIokmVCqZ7FMCQy+NSRdqGsUIk60ESMH+F5nnOeEX2+pN7hhj1cS6ezGSH/jmrzw9npd8/S9hr+AQjcJNnKDLLGIeKfhqPYvQ0kpgwvsPs0mVMlBHsDPEKisMI5Fg9wOjpDFTjsKnMNuVGaXt31IwI7YCvisAEO89tzPdY+LWn7dA2mhJB7cagfSVVwJasyyBzv/UrCnecgDzTIsOBp26b0//B0K+1ZFrQAnH+39Rk65JxSojoN/M7z4xBvpMwd2nUFrZinNg+lLS7RDF3AY6UA0G/G9+esIeV27SK9v/le9f6COwUMyg/vg93xQdYQ+Y1YJBxYL+2Z2yofI9/26DvgjvTLcUCX8/i20fRcJjOZlD80tYOm9KDPGXeCH1oX4/3e1Vdz/56ZkUXbnAoZpsyJbiJwG7fDJq77rzxp+o0sjKX10vQjm/c0SYa+knx6td/1GIGywTxfH29/kFFGUqYIfjTi7atxURHMN3gHt3TvpEhkJuf+ik4SAnrYGTis9tem4OxXx1CO9CZhkEs0/LSBVJkkOGla/N2C2wDxdDjEYmZtIO/LUUvaoBJDuyiLp/tMp7i/hszEGGZ+iou4ddguQdzRRvf7YfnumV4y76dckZdMJOflUN9Bj9cXmcr1Sv3B/AWVKdchjeQjj2esCWh/4tPvwKP14U=
