sudo: required

language: python

services:
- docker

before_install:
- docker pull sanji/mosquitto-dev
- docker images

script:
- bash build.sh

addons:
  artifacts:
    paths:
    - $(ls workspace/*.deb | tr "\n" ":")